# Generated by Django 5.1 on 2025-02-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enquiry_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=25)),
                ('text', models.CharField(max_length=800)),
                ('message', models.CharField(max_length=10000)),
            ],
        ),
    ]
