# Generated by Django 5.1 on 2025-02-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry_table',
            name='text',
        ),
        migrations.AddField(
            model_name='enquiry_table',
            name='subject',
            field=models.CharField(default=255, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquiry_table',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='enquiry_table',
            name='message',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='enquiry_table',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
